// <auto-generated />
using System;
using Cryptomind.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cryptomind.Data.Migrations
{
    [DbContext(typeof(CryptomindDbContext))]
    [Migration("20260224034914_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cipher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowHint")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSolution")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowTypeHint")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChallengeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DecryptedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedText")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLLMRecommended")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlaintextValid")
                        .HasColumnType("bit");

                    b.Property<string>("MLPrediction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TypeOfCipher")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EncryptedText")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Cipher");

                    b.HasDiscriminator<string>("EntityType").HasValue("Cipher");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.AnswerSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CipherId")
                        .HasColumnType("int");

                    b.Property<string>("DecryptedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UplodaedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CipherId");

                    b.HasIndex("UserId", "CipherId", "DecryptedText")
                        .IsUnique();

                    b.ToTable("AnswerSuggestions");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AttemptedCiphers")
                        .HasColumnType("int");

                    b.Property<string>("BanReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeactivated")
                        .HasColumnType("bit");

                    b.Property<int>("LeaderBoardPlace")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            AccessFailedCount = 0,
                            AttemptedCiphers = 0,
                            ConcurrencyStamp = "a6de731b-2258-4773-998f-115edcc37a43",
                            Email = "admin@cryptomind.com",
                            EmailConfirmed = true,
                            IsBanned = false,
                            IsDeactivated = false,
                            LeaderBoardPlace = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CRYPTOMIND.COM",
                            NormalizedUserName = "ADMIN@CRYPTOMIND.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDljVwiXOjQ1i3lObm+Q6gepHa/3pY5LjM9c8pnfw7a3/EKKPj7LKr8hfKbcDfaxaQ==",
                            PhoneNumberConfirmed = false,
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 0,
                            SecurityStamp = "a1a1a1a1-b2b2-c3c3-d4d4-e5e5e5e5e5e5",
                            SolvedCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin@cryptomind.com"
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            AccessFailedCount = 0,
                            AttemptedCiphers = 0,
                            ConcurrencyStamp = "8796aa41-091d-4d95-b256-e0e9d0b785bc",
                            Email = "user@cryptomind.com",
                            EmailConfirmed = true,
                            IsBanned = false,
                            IsDeactivated = false,
                            LeaderBoardPlace = 0,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@CRYPTOMIND.COM",
                            NormalizedUserName = "USER@CRYPTOMIND.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELLnHUhDH0eMIU6bXaQaC88GHO3MTRi8DhlCotEHX5gy5KEIgjzTS79/pWCR3bikMQ==",
                            PhoneNumberConfirmed = false,
                            RegisteredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 0,
                            SecurityStamp = "f6f6f6f6-e5e5-d4d4-c3c3-b2b2b2b2b2b2",
                            SolvedCount = 0,
                            TwoFactorEnabled = false,
                            UserName = "user@cryptomind.com"
                        });
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EarnedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Solve your first cipher",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_1.png",
                            Title = "First Blood"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Solve 25 ciphers",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_2.png",
                            Title = "Apprentice Cryptanalyst"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Solve 50 ciphers",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_3.png",
                            Title = "Seasoned Decoder"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Description = "Solve 100 ciphers",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_4.png",
                            Title = "Master Cryptanalyst"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Description = "Solve ciphers from 5 different types",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_5.png",
                            Title = "Diverse Solver"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            Description = "Solve ciphers from 10 different types",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_6.png",
                            Title = "Polyglot Decoder"
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            Description = "Have your first cipher approved",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_7.png",
                            Title = "Cipher Creator"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Description = "Have 5 ciphers approved",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_8.png",
                            Title = "Community Contributor"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Description = "Have 15 ciphers approved",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_9.png",
                            Title = "Architect of Ciphers"
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Description = "First approved suggested answer",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_10.png",
                            Title = "Helpful Mind"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Description = "10 approved suggested answers",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_11.png",
                            Title = "Trusted Contributor"
                        },
                        new
                        {
                            Id = 12,
                            Category = 0,
                            Description = "Solve 10 ciphers without using hints",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_12.png",
                            Title = "No Mercy"
                        },
                        new
                        {
                            Id = 13,
                            Category = 0,
                            Description = "Solve 10 ciphers correctly on the first attempt",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_13.png",
                            Title = "Flawless Solver"
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            Description = "Use hints on 25 different ciphers",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_14.png",
                            Title = "Curious Mind"
                        },
                        new
                        {
                            Id = 15,
                            Category = 0,
                            Description = "Solve a cipher solved by fewer than 3 users",
                            EarnedBy = 0,
                            ImagePath = "../Images/Badges/Badge_15.png",
                            Title = "Against the Odds"
                        });
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.CipherTag", b =>
                {
                    b.Property<int>("CipherId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("CipherId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CipherTags");

                    b.HasData(
                        new
                        {
                            CipherId = 1,
                            TagId = 6
                        },
                        new
                        {
                            CipherId = 1,
                            TagId = 4
                        },
                        new
                        {
                            CipherId = 2,
                            TagId = 3
                        },
                        new
                        {
                            CipherId = 2,
                            TagId = 6
                        },
                        new
                        {
                            CipherId = 3,
                            TagId = 3
                        },
                        new
                        {
                            CipherId = 3,
                            TagId = 4
                        },
                        new
                        {
                            CipherId = 4,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 4,
                            TagId = 7
                        },
                        new
                        {
                            CipherId = 5,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 5,
                            TagId = 7
                        },
                        new
                        {
                            CipherId = 6,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 6,
                            TagId = 7
                        },
                        new
                        {
                            CipherId = 6,
                            TagId = 5
                        },
                        new
                        {
                            CipherId = 7,
                            TagId = 3
                        },
                        new
                        {
                            CipherId = 7,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 8,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 8,
                            TagId = 4
                        },
                        new
                        {
                            CipherId = 9,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 9,
                            TagId = 7
                        },
                        new
                        {
                            CipherId = 10,
                            TagId = 6
                        },
                        new
                        {
                            CipherId = 10,
                            TagId = 4
                        },
                        new
                        {
                            CipherId = 11,
                            TagId = 6
                        },
                        new
                        {
                            CipherId = 11,
                            TagId = 5
                        },
                        new
                        {
                            CipherId = 12,
                            TagId = 6
                        },
                        new
                        {
                            CipherId = 12,
                            TagId = 4
                        },
                        new
                        {
                            CipherId = 13,
                            TagId = 6
                        },
                        new
                        {
                            CipherId = 13,
                            TagId = 4
                        },
                        new
                        {
                            CipherId = 14,
                            TagId = 3
                        },
                        new
                        {
                            CipherId = 14,
                            TagId = 7
                        },
                        new
                        {
                            CipherId = 15,
                            TagId = 2
                        },
                        new
                        {
                            CipherId = 15,
                            TagId = 7
                        },
                        new
                        {
                            CipherId = 15,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.HintRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CipherId")
                        .HasColumnType("int");

                    b.Property<string>("HintContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HintType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CipherId");

                    b.HasIndex("UserId");

                    b.ToTable("HintRequests");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            Type = 4
                        },
                        new
                        {
                            Id = 5,
                            Type = 5
                        },
                        new
                        {
                            Id = 6,
                            Type = 6
                        },
                        new
                        {
                            Id = 7,
                            Type = 7
                        });
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadge");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.UserSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CipherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeSolved")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsedFullSolution")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedSolutionHint")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedTypeHint")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CipherId");

                    b.HasIndex("UserId", "CipherId")
                        .IsUnique()
                        .HasFilter("[IsCorrect] = 1");

                    b.ToTable("UserSolution");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-0123-defa-234567890123",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            RoleId = "c3d4e5f6-a7b8-9012-cdef-123456789012"
                        },
                        new
                        {
                            UserId = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            RoleId = "d4e5f6a7-b8c9-0123-defa-234567890123"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.ImageCipher", b =>
                {
                    b.HasBaseType("Cipher");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OCRConfidence")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ImageCipher");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.TextCipher", b =>
                {
                    b.HasBaseType("Cipher");

                    b.HasDiscriminator().HasValue("TextCipher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Cryptography is the practice of securing information by transforming it into an unreadable format. Only those with the correct key can decode the message and read its original contents.",
                            EncryptedText = "Pbclgbtencul vf gur cenpgvpr bs frphevat vasbezngvba ol genafsbezvat vg vagb na haernqnoyr sbezng. Bayl gubfr jvgu gur pbeerpg xrl pna qrpbqr gur zrffntr naq ernq vgf bevtvany pbagragf.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "ROT13",
                            Points = 10,
                            Status = 1,
                            Title = "The ROT13 Challenge",
                            TypeOfCipher = 3
                        },
                        new
                        {
                            Id = 2,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "The art of war is of vital importance to the state. It is a matter of life and death, a road either to safety or to ruin. Hence it is a subject of inquiry which can on no account be neglected.",
                            EncryptedText = "Wkh duw ri zdu lv ri ylwdo lpsruwdqfh wr wkh vwdwh. Lw lv d pdwwhu ri olih dqg ghdwk, d urdg hlwkhu wr vdihwb ru wr uxlq. Khqfh lw lv d vxemhfw ri lqtxlub zklfk fdq rq qr dffrxqw eh qhjohfwhg.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Caesar",
                            Points = 10,
                            Status = 1,
                            Title = "Caesar's Secret",
                            TypeOfCipher = 0
                        },
                        new
                        {
                            Id = 3,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "The system of cryptography depends on the strongness of mathematical problems that are believed to be computationally intractable. The secrets of modern encryption rest on this foundation.",
                            EncryptedText = "Gsv hbhgvn lu xibkgltizksb wvkvmwh lm gsv hgizmtgsvm lu nzgsvnzgrixzo kiliyovnh gszg ziv yvorvevw gl yv xlnkfgzgrlmzoob rmgizxgzyov. Gsv hvxfirgh lu nlwvim vmxibkgrlm ivhg lm gsrh ulfmwzgrlm.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Atbash",
                            Points = 15,
                            Status = 1,
                            Title = "Mirror of Letters",
                            TypeOfCipher = 1
                        },
                        new
                        {
                            Id = 4,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Following old habits can keep you at an undesired place. Remove insight from the role to reach and reveal one's keys. Understanding the subtleness of the representations is the deep insight.",
                            EncryptedText = "Xbyybdwhn oxo thyepc iye xc kj exoyuncxwnh cwzbo. Kbbenh xwcejke tybw mbn jyzb ze dbyobex bde'c tbnc. Ynobycezwowhn exn cbljybcco bq zbn ynjybcbnezexobwc oc exn monp xwcocnex.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "SimpleSubstitution",
                            Points = 25,
                            Status = 1,
                            Title = "Scrambled Alphabet",
                            TypeOfCipher = 2
                        },
                        new
                        {
                            Id = 5,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Cryptology is the art of hiding information beyond its statistical qualities. The key is a word used to encode and decode the message based on a road map.",
                            EncryptedText = "Lxfopvefrnhr xh qsi zyg yv aimgmrk mrhsvqexmsr fciymrk mxw wxexmwxmgep uyepmxmiw. Xli cli mw e asv ywih xs irgsHi erh higsHi xli qiwweki fewiH sr e vseH qex.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Vigenere",
                            Points = 30,
                            Status = 1,
                            Title = "The Vigenere Veil",
                            TypeOfCipher = 4
                        },
                        new
                        {
                            Id = 6,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Autokey is a sophistication where the key changes automatically based on the plaintext itself. This renders it significantly more secure than standard polyalphabetic ciphers.",
                            EncryptedText = "Bpsxozgfmz al i kmzbsyblqkibqwv aowabsz cvsfs bvs zsg qvivusa iybwzibqkittr pibsr wv bvs xtiqvbslb qbastd. Bvqa zmvrsza qb awuvoqkivbtr uwfs lmkgem bviv abivrivp xwtritxvibsmqk kqxvsfl.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Autokey",
                            Points = 35,
                            Status = 1,
                            Title = "Autokey Enigma",
                            TypeOfCipher = 5
                        },
                        new
                        {
                            Id = 7,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Trithemius is a polyalphabetic cipher, where the alphabet is shifted in a regular manner without any key. The result is a regular moving state of the alphabet shifted in order.",
                            EncryptedText = "Alcru lr t uidlbxevlypyu mltrag, qsxpxr max tufetmlx lv yaxnxw lq t pxznetm ftqqxo ulmaxry tgr uxr. Qeb exjbiv fp t pxznetm nlqfqz pftcx bq max tufetmax ualmary mr fqvbq.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Trithemius",
                            Points = 30,
                            Status = 1,
                            Title = "The Trithemius Ladder",
                            TypeOfCipher = 6
                        },
                        new
                        {
                            Id = 8,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Transposition of information can be described decoded by discovering the statistical structure of the text. The letters are rearranged in a zigzag pattern across multiple rails.",
                            EncryptedText = "Tersoi snomto aefnaifrtnoi cne eb dseeicrphd sdneoeircd yb giieosnvbr het attniclstiias rrutscuet fo het ttxe. Het eltters rea rea rneadgrar ni a zagigzag ttanrep scroass plutefilm sialr.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "RailFence",
                            Points = 20,
                            Status = 1,
                            Title = "The Rail Fence",
                            TypeOfCipher = 7
                        },
                        new
                        {
                            Id = 9,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Information is arranged in rows and columns, then read off by column in a specific order. The key determines the order in which the columns are read to recover the plaintext.",
                            EncryptedText = "Iitmnofra si darre ni wors nda ulnocsm, hnet arde fof yb ncolum ni a pecifsi rerod. Teh yke medinretes eth rored ni hcwhi hte nlomcsu rae arde ot decor teh tpxtliean.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Columnar",
                            Points = 25,
                            Status = 1,
                            Title = "The Columnar Maze",
                            TypeOfCipher = 8
                        },
                        new
                        {
                            Id = 10,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Base64 is not an encryption mechanism but an encoding format that represents binary data in an ASCII string format using sixty-four characters.",
                            EncryptedText = "QmFzZTY0IGlzIG5vdCBhbiBlbmNyeXB0aW9uIG1lY2hhbmlzbSBidXQgYW4gZW5jb2RpbmcgZm9ybWF0IHRoYXQgcmVwcmVzZW50cyBiaW5hcnkgZGF0YSBpbiBhbiBBU0NJSSBzdHJpbmcgZm9ybWF0IHVzaW5nIHNpeHR5LWZvdXIgY2hhcmFjdGVycy4=",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Base64",
                            Points = 10,
                            Status = 1,
                            Title = "The Base64 Barrier",
                            TypeOfCipher = 10
                        },
                        new
                        {
                            Id = 11,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "MORSE CODE IS NOT A CIPHER BUT AN ENCODING SYSTEM THAT REPRESENTS LETTERS AS SEQUENCES OF DOTS AND DASHES",
                            EncryptedText = "-- --- .-. ... . / -.-. --- -.. . / .. ... / -. --- - / .- / -.-. .. .--. .... . .-. / -... ..- - / .- -. / . -. -.-. --- -.. .. -. --. / ... -.-- ... - . -- / - .... .- - / .-. . .--. .-. . ... . -. - ... / .-.. . - - . .-. ... / .- ... / ... . --.- ..- . -. -.-. . ... / --- ..-. / -.. --- - ... / .- -. -.. / -.. .- ... .... . .",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Morse",
                            Points = 10,
                            Status = 1,
                            Title = "Dots and Dashes",
                            TypeOfCipher = 11
                        },
                        new
                        {
                            Id = 12,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Binary uses zeros and ones",
                            EncryptedText = "01000010 01101001 01101110 01100001 01110010 01111001 00100000 01110101 01110011 01100101 01110011 00100000 01111010 01100101 01110010 01101111 01110011 00100000 01100001 01101110 01100100 00100000 01101111 01101110 01100101 01110011",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Binary",
                            Points = 10,
                            Status = 1,
                            Title = "The Binary Message",
                            TypeOfCipher = 12
                        },
                        new
                        {
                            Id = 13,
                            AllowHint = true,
                            AllowSolution = true,
                            AllowTypeHint = true,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Hex encoding represents data using sixteen distinct symbols from the hexadecimal number system, using digits zero through nine and letters a through f for values ten to fifteen",
                            EncryptedText = "48657820656e636f64696e6720726570726573656e74732064617461207573696e672073697874656574206469737469 6e637420737 96d626f6c73 2066726f6d 207468652068657861646563696d616c206e756d626572207379737465 6d2c207573696e67206469676974732030207468726f75676820392061 6e64206c657474657273206120 7468726f756768206620 666f722076616c7565732074656e20746f2066696674656 56e",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Hex",
                            Points = 10,
                            Status = 1,
                            Title = "Hex Decoded",
                            TypeOfCipher = 13
                        },
                        new
                        {
                            Id = 14,
                            AllowHint = true,
                            AllowSolution = false,
                            AllowTypeHint = false,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 0,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            DecryptedText = "Perhaps exists a difference between information and intelligence. One is a more lasting on passing details round, the other is a more solidling by wearing from a wider picku. Only those who can ciphers rise based on fals.",
                            EncryptedText = "Mnjpncn rflbcb l asfmncnwln unwonnw jwxfanzlcrxw lwm jwcnuurpnwln. Cwn rb l exfn qlacrwp xw ylabrwp mncluub fxdwm, cwn xcsnf rb l sxfn bxurmurwp eq dwnlfrwp qfxz l efrmnf yrnad. Xwuq csxbn tsx alw arqsncb frnb elbnm xw qlab.",
                            IsDeleted = false,
                            IsLLMRecommended = false,
                            IsPlaintextValid = true,
                            MLPrediction = "Caesar",
                            Points = 20,
                            Status = 1,
                            Title = "Julius's Whisper",
                            TypeOfCipher = 0
                        },
                        new
                        {
                            Id = 15,
                            AllowHint = false,
                            AllowSolution = false,
                            AllowTypeHint = false,
                            ApprovedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChallengeType = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            EncryptedText = "Pbzr byhgvbaf ner abg ernqvyl xabja. Guvf zrffntr znl or rapelcgrq jvgu n pvcure gung unf ab pbasvezrq fbyhgvba. Lbhe gnfx vf gb fghql gur cnggrea, fhttrfg n cbffvoyr zrgubq, naq fhowzvg lbhe ernfbarq thrff sbe pbzzhavgl irevsvpngvba.",
                            IsDeleted = false,
                            IsLLMRecommended = true,
                            IsPlaintextValid = false,
                            MLPrediction = "Vigenere",
                            Points = 50,
                            Status = 1,
                            Title = "The Unknown Veil"
                        });
                });

            modelBuilder.Entity("Cipher", b =>
                {
                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany("UploadedCiphers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CipherLLMData", "LLMData", b1 =>
                        {
                            b1.Property<int>("CipherId")
                                .HasColumnType("int");

                            b1.Property<string>("CachedHint")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CachedSolution")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CachedTypeHint")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Confidence")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("IsAppropriate")
                                .HasColumnType("bit");

                            b1.Property<bool?>("IsSolvable")
                                .HasColumnType("bit");

                            b1.Property<string>("Issues")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PredictedType")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Reasoning")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("SolutionCorrect")
                                .HasColumnType("bit");

                            b1.HasKey("CipherId");

                            b1.ToTable("Cipher");

                            b1.WithOwner()
                                .HasForeignKey("CipherId");

                            b1.HasData(
                                new
                                {
                                    CipherId = 1,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "ROT13",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 2,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Caesar",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 3,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Atbash",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 4,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "SimpleSubstitution",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 5,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Vigenere",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 6,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Autokey",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 7,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Trithemius",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 8,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "RailFence",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 9,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "Medium",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Columnar",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 10,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Base64",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 11,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Morse",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 12,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Binary",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 13,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Hex",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 14,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "High",
                                    IsAppropriate = true,
                                    IsSolvable = true,
                                    PredictedType = "Caesar",
                                    SolutionCorrect = true
                                },
                                new
                                {
                                    CipherId = 15,
                                    CachedHint = "",
                                    CachedSolution = "",
                                    CachedTypeHint = "",
                                    Confidence = "Medium",
                                    IsAppropriate = true,
                                    PredictedType = "Vigenere"
                                });
                        });

                    b.Navigation("CreatedByUser");

                    b.Navigation("LLMData");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.AnswerSuggestion", b =>
                {
                    b.HasOne("Cipher", "Cipher")
                        .WithMany("AnswerSuggestions")
                        .HasForeignKey("CipherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("SuggestedAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Cipher");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.CipherTag", b =>
                {
                    b.HasOne("Cipher", "Cipher")
                        .WithMany("CipherTags")
                        .HasForeignKey("CipherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cryptomind.Data.Entities.Tag", "Tag")
                        .WithMany("CipherTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cipher");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.HintRequest", b =>
                {
                    b.HasOne("Cipher", "Cipher")
                        .WithMany("HintsRequested")
                        .HasForeignKey("CipherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("HintsRequested")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Cipher");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.Notification", b =>
                {
                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.UserBadge", b =>
                {
                    b.HasOne("Cryptomind.Data.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.UserSolution", b =>
                {
                    b.HasOne("Cipher", "Cipher")
                        .WithMany("UserSolutions")
                        .HasForeignKey("CipherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", "User")
                        .WithMany("CipherAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cipher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Cryptomind.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cipher", b =>
                {
                    b.Navigation("AnswerSuggestions");

                    b.Navigation("CipherTags");

                    b.Navigation("HintsRequested");

                    b.Navigation("UserSolutions");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("CipherAnswers");

                    b.Navigation("HintsRequested");

                    b.Navigation("Notifications");

                    b.Navigation("SuggestedAnswers");

                    b.Navigation("UploadedCiphers");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Cryptomind.Data.Entities.Tag", b =>
                {
                    b.Navigation("CipherTags");
                });
#pragma warning restore 612, 618
        }
    }
}
